/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/_authenticated/submissions'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQualitiesRouteImport } from './routes/_authenticated/qualities'
import { Route as AuthenticatedMachinesRouteImport } from './routes/_authenticated/machines'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedJobworkersRouteImport } from './routes/_authenticated/jobworkers'
import { Route as AuthenticatedBeamsRouteImport } from './routes/_authenticated/beams'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubmissionsRoute =
  AuthenticatedSubmissionsRouteImport.update({
    id: '/_authenticated/submissions',
    path: '/submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQualitiesRoute = AuthenticatedQualitiesRouteImport.update({
  id: '/_authenticated/qualities',
  path: '/qualities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMachinesRoute = AuthenticatedMachinesRouteImport.update({
  id: '/_authenticated/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/_authenticated/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJobworkersRoute = AuthenticatedJobworkersRouteImport.update({
  id: '/_authenticated/jobworkers',
  path: '/jobworkers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBeamsRoute = AuthenticatedBeamsRouteImport.update({
  id: '/_authenticated/beams',
  path: '/beams',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/beams': typeof AuthenticatedBeamsRoute
  '/jobworkers': typeof AuthenticatedJobworkersRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/machines': typeof AuthenticatedMachinesRoute
  '/qualities': typeof AuthenticatedQualitiesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/beams': typeof AuthenticatedBeamsRoute
  '/jobworkers': typeof AuthenticatedJobworkersRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/machines': typeof AuthenticatedMachinesRoute
  '/qualities': typeof AuthenticatedQualitiesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/beams': typeof AuthenticatedBeamsRoute
  '/_authenticated/jobworkers': typeof AuthenticatedJobworkersRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/machines': typeof AuthenticatedMachinesRoute
  '/_authenticated/qualities': typeof AuthenticatedQualitiesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/beams'
    | '/jobworkers'
    | '/ledger'
    | '/machines'
    | '/qualities'
    | '/settings'
    | '/submissions'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/beams'
    | '/jobworkers'
    | '/ledger'
    | '/machines'
    | '/qualities'
    | '/settings'
    | '/submissions'
    | '/'
  id:
    | '__root__'
    | '/_authenticated/beams'
    | '/_authenticated/jobworkers'
    | '/_authenticated/ledger'
    | '/_authenticated/machines'
    | '/_authenticated/qualities'
    | '/_authenticated/settings'
    | '/_authenticated/submissions'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedBeamsRoute: typeof AuthenticatedBeamsRoute
  AuthenticatedJobworkersRoute: typeof AuthenticatedJobworkersRoute
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedMachinesRoute: typeof AuthenticatedMachinesRoute
  AuthenticatedQualitiesRoute: typeof AuthenticatedQualitiesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/submissions': {
      id: '/_authenticated/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/qualities': {
      id: '/_authenticated/qualities'
      path: '/qualities'
      fullPath: '/qualities'
      preLoaderRoute: typeof AuthenticatedQualitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/machines': {
      id: '/_authenticated/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof AuthenticatedMachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jobworkers': {
      id: '/_authenticated/jobworkers'
      path: '/jobworkers'
      fullPath: '/jobworkers'
      preLoaderRoute: typeof AuthenticatedJobworkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/beams': {
      id: '/_authenticated/beams'
      path: '/beams'
      fullPath: '/beams'
      preLoaderRoute: typeof AuthenticatedBeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedBeamsRoute: AuthenticatedBeamsRoute,
  AuthenticatedJobworkersRoute: AuthenticatedJobworkersRoute,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedMachinesRoute: AuthenticatedMachinesRoute,
  AuthenticatedQualitiesRoute: AuthenticatedQualitiesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
